In [1]:
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('max_rows', 10)
pd.options.display.float_format = '{:.1f}'.format

In [2]:
data = pd.read_csv('vibory_data.csv')

In [3]:
data

,Регион,ТИК,УИК,"Число избирателей, включенных в список избирателей","Число избирательных бюллетеней, полученных участковой избирательной комиссией","Число избирательных бюллетеней, выданных избирателям, проголосовавшим досрочно","Число избирательных бюллетеней, выданных в помещении для голосования в день голосования","Число избирательных бюллетеней, выданных вне помещения для голосования в день голосования",Число погашенных избирательных бюллетеней,Число избирательных бюллетеней в переносных ящиках для голосования,Число бюллетеней в стационарных ящиках для голосования,Число недействительных избирательных бюллетеней,Число действительных избирательных бюллетеней,Число утраченных избирательных бюллетеней,"Число избирательных бюллетеней, не учтенных при получении",Бабурин Сергей Николаевич,Грудинин Павел Николаевич,Жириновский Владимир Вольфович,Путин Владимир Владимирович,Собчак Ксения Анатольевна,Сурайкин Максим Александрович,Титов Борис Юрьевич,Явлинский Григорий Алексеевич
0,Республика Адыгея (Адыгея),Адыгейская,1,2256,2181,0,2107,62,12,62,2107,3,2166,0,0,0,137,32,1977,14,0,1,5
1,Республика Адыгея (Адыгея),Адыгейская,2,2700,2633,0,2575,41,17,41,2575,22,2594,0,0,15,86,65,2389,13,5,6,15
2,Республика Адыгея (Адыгея),Адыгейская,3,2858,2752,0,2664,75,13,75,2664,5,2734,0,0,1,62,13,2645,6,3,4,0
3,Республика Адыгея (Адыгея),Адыгейская,4,2066,2034,0,1857,142,35,142,1857,21,1978,0,0,5,288,12,1642,21,6,2,2
4,Республика Адыгея (Адыгея),Адыгейская,5,700,714,0,676,11,27,11,676,3,684,0,0,2,44,6,624,6,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97690,Территория за пределами РФ,Территория за пределами РФ,8433,436,2500,0,431,5,2064,5,431,0,436,0,0,3,32,13,371,8,3,3,3
97691,Территория за пределами РФ,Территория за пределами РФ,8434,1141,3000,0,1136,5,1859,5,1136,44,1097,0,0,1,10,5,1072,8,1,0,0
97692,Территория за пределами РФ,Территория за пределами РФ,8436,78,1507,0,78,0,1429,0,78,0,78,0,0,0,17,3,43,10,0,3,2
97693,Территория за пределами РФ,Территория за пределами РФ,8437,848,2500,0,743,105,1652,105,743,36,812,0,0,4,4,0,802,1,1,0,0
97694,Территория за пределами РФ,Территория за пределами РФ,8443,2004,4000,0,1978,26,1995,26,1977,69,1934,1,0,23,36,21,1835,8,5,3,3

явку (%) по всем регионам, результат отсортировать по убыванию

In [4]:
data['Явка'] = data.iloc[:, 12] / data.iloc[:, 3] * 100

In [5]:
data.sort_values('Явка', ascending= False)

,Регион,ТИК,УИК,"Число избирателей, включенных в список избирателей","Число избирательных бюллетеней, полученных участковой избирательной комиссией","Число избирательных бюллетеней, выданных избирателям, проголосовавшим досрочно","Число избирательных бюллетеней, выданных в помещении для голосования в день голосования","Число избирательных бюллетеней, выданных вне помещения для голосования в день голосования",Число погашенных избирательных бюллетеней,Число избирательных бюллетеней в переносных ящиках для голосования,Число бюллетеней в стационарных ящиках для голосования,Число недействительных избирательных бюллетеней,Число действительных избирательных бюллетеней,Число утраченных избирательных бюллетеней,"Число избирательных бюллетеней, не учтенных при получении",Бабурин Сергей Николаевич,Грудинин Павел Николаевич,Жириновский Владимир Вольфович,Путин Владимир Владимирович,Собчак Ксения Анатольевна,Сурайкин Максим Александрович,Титов Борис Юрьевич,Явлинский Григорий Алексеевич,Явка
33311,Архангельская область,"Архангельск, Соломбальская",127,53,53,0,28,25,0,25,28,0,53,0,0,0,0,3,49,1,0,0,0,100.0
12952,Республика Татарстан (Татарстан),Апастовская,893,185,186,0,177,8,1,8,177,0,185,0,0,0,3,0,182,0,0,0,0,100.0
1686,Республика Башкортостан,Зилаирская,2002,143,169,0,143,0,26,0,143,0,143,0,0,1,15,3,122,0,1,1,0,100.0
21747,Камчатский край,Петропавловск-Камчатская городская (судовая),267,14,14,0,14,0,0,0,14,0,14,0,0,0,8,1,5,0,0,0,0,100.0
21746,Камчатский край,Петропавловск-Камчатская городская (судовая),266,14,16,0,14,0,2,0,14,0,14,0,0,2,3,7,2,0,0,0,0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,Республика Крым,"Симферополь, Киевская",353,1997,1750,0,406,25,1319,25,406,5,426,0,0,1,15,4,342,46,0,3,15,21.3
9642,Республика Крым,"Симферополь, Киевская",351,1963,1700,0,405,13,1282,13,405,9,409,0,0,1,12,7,337,39,1,2,10,20.8
54106,Московская область,Балашихинская городская,3668,1331,1200,0,863,23,314,22,239,1,260,0,0,1,39,13,189,9,1,1,7,19.5
28765,Приморский край,Артёмовская городская,326,1140,1100,0,927,36,137,36,805,758,83,0,0,1,22,5,52,2,1,0,0,7.3
11409,Республика Саха (Якутия),Булунская,809,7,7,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0

выберите произвольного кандидата и найдите тот избиратльный участок, на котором он получил наибольший результат (%, учитывать участки на которых проголосовало больше 300 человек)

Сурайкин

In [6]:
temp = data[data.iloc[:, 12] > 300]

In [7]:
(temp.iloc[:, 20] / temp.iloc[:, 12] * 100).max()

16.061452513966483

In [10]:
idxmax = (temp.iloc[:, 20] / temp.iloc[:, 12] * 100).idxmax()

In [11]:
data.iloc[idxmax, [0, 1, 2, 20]]

Регион                           Республика Северная Осетия - Алания
ТИК                                        Владикавказ, Левобережная
УИК                                                              329
Сурайкин Максим Александрович                                    230
Name: 12240, dtype: object

найдите регион, где разница между ТИК с наибольшей явкой и наименьшей максимальна

In [12]:
temp = data.groupby(['Регион', 'ТИК']).apply(lambda x : x.iloc[:, 12].sum()).to_frame().reset_index() \
.groupby('Регион')[0].apply(lambda x : x.max() - x.min())

In [13]:
temp.max()

193174

In [14]:
temp.idxmax()

'Самарская область'

посчитайте дисперсию по явке для каждого региона (учитывать УИК)

In [15]:
data.groupby('Регион')['Явка'].var()

Регион
Алтайский край                     97.4
Амурская область                  135.9
Архангельская область             193.8
Астраханская область              123.9
Белгородская область              191.0
                                   ...
Ямало-Ненецкий автономный округ    88.4
Ярославская область                73.4
город Москва                       77.5
город Санкт-Петербург             133.8
город Севастополь                  45.1
Name: Явка, Length: 87, dtype: float64

для каждого кандидата посчитайте таблицу: результат (%, округленный до целого) - количество УИК, на которых кандидат получил данный результат

In [16]:
overall = (data.iloc[:, 15:23].div(data.iloc[:, 12], axis= 0) * 100).round()

In [17]:
overall.iloc[:, 0].value_counts().to_frame()

      Бабурин Сергей Николаевич
1.0                       48112
0.0                       44728
2.0                        3919
3.0                         547
4.0                         183
...                         ...
12.0                          1
44.0                          1
23.0                          1
17.0                          1
13.0                          1

[22 rows x 1 columns]

In [18]:
overall.iloc[:, 1].value_counts().to_frame()

      Грудинин Павел Николаевич
12.0                       8037
11.0                       7532
13.0                       7227
10.0                       6874
14.0                       6233
...                         ...
60.0                          1
61.0                          1
80.0                          1
71.0                          1
75.0                          1

[68 rows x 1 columns]

In [19]:
overall.iloc[:, 2].value_counts().to_frame()

      Жириновский Владимир Вольфович
6.0                            13599
5.0                            13078
7.0                            11878
4.0                             9912
8.0                             8988
...                              ...
48.0                               1
96.0                               1
47.0                               1
53.0                               1
78.0                               1

[55 rows x 1 columns]

In [20]:
overall.iloc[:, 3].value_counts().to_frame()

      Путин Владимир Владимирович
75.0                         5718
76.0                         5704
77.0                         5369
74.0                         5343
73.0                         4996
...                           ...
19.0                            1
34.0                            1
4.0                             1
0.0                             1
22.0                            1

[92 rows x 1 columns]

In [21]:
overall.iloc[:, 4].value_counts().to_frame()

      Собчак Ксения Анатольевна
1.0                       36062
0.0                       27778
2.0                       18725
3.0                        7921
4.0                        3647
...                         ...
21.0                          1
37.0                          1
31.0                          1
28.0                          1
29.0                          1

[32 rows x 1 columns]

In [22]:
overall.iloc[:, 5].value_counts().to_frame()

      Сурайкин Максим Александрович
1.0                           49063
0.0                           43076
2.0                            4099
3.0                             785
4.0                             253
...                             ...
18.0                              2
15.0                              1
17.0                              1
16.0                              1
14.0                              1

[18 rows x 1 columns]

In [23]:
overall.iloc[:, 6].value_counts().to_frame()

      Титов Борис Юрьевич
0.0                 49593
1.0                 40079
2.0                  6797
3.0                   896
4.0                   181
...                   ...
13.0                    1
29.0                    1
18.0                    1
19.0                    1
12.0                    1

[22 rows x 1 columns]

In [24]:
overall.iloc[:, 7].value_counts().to_frame()

      Явлинский Григорий Алексеевич
0.0                           51052
1.0                           30818
2.0                            9160
3.0                            3763
4.0                            1613
...                             ...
18.0                              1
16.0                              1
12.0                              1
13.0                              1
21.0                              1

[21 rows x 1 columns]